# Generated by Django 3.2.19 on 2023-10-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exploreHotels', '0002_auto_20231013_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='image',
            new_name='hotel_image',
        ),
    ]
