# Generated by Django 3.2.19 on 2023-10-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exploreHotels', '0003_rename_image_hotels_hotel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='country',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='facilityoftype1',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='facilityoftype2',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='facilityoftype3',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='hearing_impaired',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='hotel_image',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='pricetype1',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='pricetype2',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='pricetype3',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='roomtype1',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='roomtype2',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='roomtype3',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='speech_impaired',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='state',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='visual_impaired',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='wheelchair_user',
        ),
    ]
