# Generated by Django 3.2.19 on 2023-10-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploreHotels', '0004_auto_20231013_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='city',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='hotels',
            name='country',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='hotels',
            name='facility',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='hotels',
            name='facilityoftype1',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='hotels',
            name='facilityoftype2',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='hotels',
            name='facilityoftype3',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='hotels',
            name='hearing_impaired',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='hotels',
            name='hotel_image',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='hotels',
            name='landmark',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='hotels',
            name='phone',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='hotels',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotels',
            name='prefix',
            field=models.CharField(default=' ', max_length=4),
        ),
        migrations.AddField(
            model_name='hotels',
            name='pricetype1',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='hotels',
            name='pricetype2',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='hotels',
            name='pricetype3',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='hotels',
            name='roomtype1',
            field=models.CharField(default='Regular', max_length=100),
        ),
        migrations.AddField(
            model_name='hotels',
            name='roomtype2',
            field=models.CharField(default='Regular', max_length=100),
        ),
        migrations.AddField(
            model_name='hotels',
            name='roomtype3',
            field=models.CharField(default='Regular', max_length=100),
        ),
        migrations.AddField(
            model_name='hotels',
            name='speech_impaired',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='hotels',
            name='state',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='hotels',
            name='visual_impaired',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='hotels',
            name='wheelchair_user',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
