# Generated by Django 3.2.19 on 2023-10-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exploreHotels', '0005_auto_20231013_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='city',
        ),
    ]
