# Generated by Django 3.2.19 on 2023-10-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exploreHotels', '0007_hotels_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='hotel_image',
            new_name='image',
        ),
    ]
