# Generated by Django 3.2.19 on 2023-10-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploreHotels', '0008_rename_hotel_image_hotels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
