# Generated by Django 3.2.19 on 2023-12-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('place_cid', models.IntegerField(default=0)),
                ('commenter_name', models.CharField(default='Default Name', max_length=200)),
                ('comment_body', models.TextField(default='comment body')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
