# Generated by Django 4.2.5 on 2023-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explore_place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=100)),
                ('visual_impaired', models.BooleanField()),
                ('wheelchair_user', models.BooleanField()),
                ('hearing_impaired', models.BooleanField()),
                ('speech_impaired', models.BooleanField()),
                ('city', models.CharField(max_length=100)),
                ('facility', models.TextField()),
                ('About', models.TextField()),
                ('location', models.CharField(max_length=500)),
            ],
        ),
    ]
