# Generated by Django 3.2.19 on 2023-10-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exploreApp', '0003_explore_place_place_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explore_place',
            name='place_image',
        ),
        migrations.RemoveField(
            model_name='explore_place',
            name='place_image1',
        ),
    ]
