# Generated by Django 3.2.19 on 2023-10-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploreApp', '0005_explore_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore_place',
            name='image',
            field=models.ImageField(default='"C:\\Users\\HP\\Pictures\\Saved Pictures\\flower.jpeg"', upload_to=''),
        ),
    ]
