# Generated by Django 3.2.19 on 2023-10-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exploreApp', '0003_alter_explore_place_image'),
        ('exploreApp', '0010_alter_explore_place_image'),
    ]

    operations = [
    ]
