# Generated by Django 3.2.19 on 2023-10-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploreApp', '0011_merge_20231012_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('landmark', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('prefix', models.CharField(max_length=4)),
                ('phone', models.CharField(max_length=10)),
                ('visual_impaired', models.BooleanField()),
                ('wheelchair_user', models.BooleanField()),
                ('hearing_impaired', models.BooleanField()),
                ('speech_impaired', models.BooleanField()),
                ('facility', models.TextField()),
                ('rooms', models.IntegerField()),
                ('price', models.IntegerField()),
                ('ac_rooms', models.BooleanField()),
            ],
        ),
    ]
