# Generated by Django 3.2.19 on 2023-10-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exploreApp', '0012_hotels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
