# Generated by Django 3.2.19 on 2023-10-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exploreApp', '0013_delete_hotels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explore_place',
            name='image',
        ),
    ]
