# Generated by Django 3.2.19 on 2023-11-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploreApp', '0014_remove_explore_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore_place',
            name='image',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
