# Generated by Django 3.2.19 on 2023-11-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteluser',
            name='hotel_profile_image',
        ),
        migrations.AddField(
            model_name='hoteluser',
            name='facility',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='hoteluser',
            name='image',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='hoteluser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
